### ISSUE TITLE
Dataset filtering details

### ISSUE THREAD

**Issue by gregorkrz** [microsoft/FS-Mol#53]
In your FS-Mol paper, it is said that only assays with 32 to 5000 compounds are kept, and the remaining training dataset then contains 4938 assays. However, if I try to filter out those from your provided dataset loading code, I'm left with ~24k assays.

```python
from fs_mol.data import FSMolDataset, DataFold
dataset = FSMolDataset.from_directory(FS_MOL_DATASET_PATH)
train_task_iterable = dataset.get_task_reading_iterable(DataFold.TRAIN)
assay_sizes = []
for t in train_task_iterable:
    assay_sizes.append(len(t.samples))
print(len(assay_sizes[np.where(np.logical_and(assay_sizes >= 32, assay_sizes <= 5000))[0]]))
# prints 23832

```
 
Is there something obvious that I'm missing?

**Comment by gregorkrz** [comment]
I see - the provided task list file needs to be used to get the exactly same results. Closing this

**Comment by megstanley** [comment]
> In your FS-Mol paper, it is said that only assays with 32 to 5000 compounds are kept, and the remaining training dataset then contains 4938 assays. However, if I try to filter out those from your provided dataset loading code, I'm left with ~24k assays.
> 
> ```python
> from fs_mol.data import FSMolDataset, DataFold
> dataset = FSMolDataset.from_directory(FS_MOL_DATASET_PATH)
> train_task_iterable = dataset.get_task_reading_iterable(DataFold.TRAIN)
> assay_sizes = []
> for t in train_task_iterable:
>     assay_sizes.append(len(t.samples))
> print(len(assay_sizes[np.where(np.logical_and(assay_sizes >= 32, assay_sizes <= 5000))[0]]))
> # prints 23832
> ```
> 
> Is there something obvious that I'm missing?

Indeed, the task list file is required. This is partly to mitigate against changes as ChEMBL is updated.
